"""created chat DB tables

Revision ID: cc14f3d67b38
Revises: c14ed54f1fba
Create Date: 2024-06-13 18:18:29.978990

"""
import sqlalchemy_file
import sqlalchemy as sa

from typing import Sequence, Union  # type: ignore
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'cc14f3d67b38'
down_revision: Union[str, None] = 'c14ed54f1fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
                    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('message', sa.Text(), nullable=False),
                    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='chat_role'), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name=op.f('chat_message_user_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('chat_message_pkey'))
                    )
    op.create_table('chat_images',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('file', sqlalchemy_file.types.ImageField(), nullable=False),
                    sa.Column('chat_id', sa.Uuid(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
                    sa.ForeignKeyConstraint(['chat_id'], ['chat_message.id'], name=op.f('chat_images_chat_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('chat_images_pkey'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_images')
    op.drop_table('chat_message')
    # ### end Alembic commands ###
