"""create table for course data

Revision ID: a3125cb6ad10
Revises: cc14f3d67b38
Create Date: 2024-06-21 16:21:27.822368

"""
from typing import Sequence, Union  # type: ignore

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3125cb6ad10'
down_revision: Union[str, None] = 'cc14f3d67b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_data',
                    sa.Column('course_id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('course_name', sa.Text(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('instructor', sa.Text(), nullable=False),
                    sa.Column('course_price', sa.INTEGER(), nullable=False),
                    sa.Column('course_timing', sa.Text(), nullable=False),
                    sa.Column('course_rating', sa.FLOAT(), nullable=True),
                    sa.Column('course_duration', sa.Text(), nullable=False),
                    sa.Column('course_status', sa.Enum('ACTIVE', 'INACTIVE', 'COMPLETED', name='coursestatus'), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
                    sa.PrimaryKeyConstraint('course_id', name=op.f('course_data_pkey'))
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_data')
    # ### end Alembic commands ###
